### ISSUE TITLE
Settings and mappings should be configurable

### ISSUE THREAD

**Issue by tylerl0706** [promptworks/elastic_sync#5]
I've come to an interesting dilemma where I would like to change the analyzer for my fields but I can't because the index already has content in it after reindexing.

I would create the index first and then reindex, but this is not possible because reindex requires that the index does not exist (at least from my knowledge). 

Perhaps the "create index" portion of reindex should be a "get or create index" and if the index already exists, attempt to fill the index with the data from Postgres.

Or, a json in the form of mappings that can be passed in to the reindex and used for the creation of the new index.

I'd be interested in working on this.

But first, a discussion on what the best option would be?

**Comment by rzane** [comment]
Yup, that's definitely an area that needs work. Here's what I was thinking:

```elixir
defmodule MyApp.SomeModel do
  use ElasticSync.Schema, index: "some_model", type: "blah"

  # This would be an overridable function.
  # The default implementation would just be an empty map.
  def elastic_sync_settings do
    # .. whatever you want
  end
end
```

This way, the developer can choose how they want to configure the mappings. If they want to load from a JSON file, that's up to them.

To implement this, you'll have to change:
* `Index.create/1`and `Index.transition` will need to take an optional argument for settings.
* `SyncRepo.reindex/2` needs to look up the settings from the schema and pass them to those functions.

What do you think?

**Comment by tylerl0706** [comment]
I like it!

In addition to settings, we can also have:

``` elixir
def mappings do
  # etc
end
```

Then we'd mimic this call:

``` bash
curl -X PUT "http://localhost:9200/$INDEX_NAME/" -d '{
    "settings":{
        "analysis":{
            "analyzer":{
                "analyzer1":{
                    "type":"custom",
                    "tokenizer":"standard",
                    "filter":[ "standard", "lowercase", "stop", "kstem", "ngram" ]
                }
            },
            "filter":{
                "ngram":{
                    "type":"ngram",
                    "min_gram":2,
                    "max_gram":15
                }
            }
        }
    },
    "mappings": {
        "product": {
            "properties": {
                "title": {
                    "type": "string",
                    "search_analyzer" : "analyzer1",
                    "index_analyzer" : "analyzer1"
                }
            }
        }
    }
}';
```

**Comment by rzane** [comment]
Yup, though I think probably just one option would be best. In which case, it probably shouldn't be called "settings" or "mappings", but perhaps just `config`.

So, that would look like this:

```elixir
defmodule MyApp.SomeModel do
  use ElasticSync.Schema,
    index: "some_model",
    type: "blah",
    config: &MyApp.SomeModel.config/0

  def index_config do
    %{settings: %{}, mappings: %{}}
  end
end
```
